
name: Test packages
run-name: Colcon test all packages
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    
jobs:
  colcon-test:
    runs-on: self-hosted
    container: 
      image: hugodelivery/ros2:overlay
      env: 
        RMW_IMPLEMENTATION: ""
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: actions/checkout@v2
    - run: |
        bash -ic "source $ROS_SOURCE && source $NAV_SOURCE && source $HUGO_SOURCE && colcon build && colcon test --return-code-on-test-failure --event-handlers console_cohesion+"
