
name: Test packages
run-name: Colcon test all packages
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      
    
jobs:
  colcon-test:
    runs-on: self-hosted
    container: 
      image: hugodelivery/ros2:overlay
      env: 
        RMW_IMPLEMENTATION: ""
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        bash -ic "source $ROS_SOURCE && source $NAV_SOURCE && source $HUGO_SOURCE && colcon build && colcon test --return-code-on-test-failure --event-handlers console_cohesion+"
